### ISSUE TITLE
1 주차 계획

### ISSUE THREAD

**Issue by gringrape** [CodeSoom/project-react-2-gringrape#1]
## 이 앱을 언제 사용하나요?
실어증 환자가 의사소통 연습을 위해 사용합니다. 실어증 환자는 이 앱을 이용해 말하고 듣고 쓰는 연습을 합니다.

첫번째 단계인 말하기는 '문장 만들기'를 통해서 연습합니다. 사용자는 제시되는 단어를 보고 빠르게
문장을 만들면서 실제 의사소통에 필요한 순발력을 기르고, 자신이 한 말을 스스로 보면서
어떤 부분이 오류인지 스스로 점검할 수 있게 됩니다. 마지막으로, 보호자에게 결과를 전달해서
대부분 고령인 환자와 매일 대면할 수 없는 보호자도 환자의 상태를 미루어 알고, 적절하게 의사소통을
진행할 수 있도록 도와줍니다. 

## 제약 조건은 무엇인가요? (문장 만들기)
- 화면에는 문장을 만들 제시어가 표시되어야 합니다 ex) 어제, 라면, 먹다
- 생각한 문장을 소리로 입력할 수 있어야 합니다.
- 만든 문장을 다시 말해서 수정할 수 있어야 합니다. 

## 구체적인 사례는 무엇인가요?
1. 연습을 시작하면 화면에 제시어가 표시됩니다. 
2. 연습자는 제시어를 사용해서 자유롭게 문장을 만들어서 말합니다.
3. 연습자는 입력된 문장을 보고 수정이 필요하면 다시 말합니다.
4-1. 스스로 다 된 것 같으면 다음 문제로 넘어갑니다.
4-2. 타이머가 다되면 다음 문제로 넘어갑니다.
5. 모든 문제를 풀면 보호자와 환자(연습자)의 메일로 결과가 전송되고 문제와 답안을 확인할 수 있습니다. 

### 1. 환경설정
- [x] Hello React 표시
- [x] 테스팅 환경 설정
- [x] eslint 설정

### 2. 음성 인식 API 학습
- [x] 사용 방법 학습
- [x] 입력 예제 작성
- [x] API 선정 - [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API) [#선정이유](https://github.com/CodeSoom/project-react-2-gringrape/issues/2#issuecomment-728191417)

### 3. 한 문장 만들기 구현 (최초 사용 가능 버전 만들기)
- [x] 화면 스케치
- [x] 화면 설계 도안 작성
- [x] 화면 중앙에 제시어 표시 #4 
- [x] 주어진 문장을 화면에 표시 #4 
- [x] 문장 입력하기 #5 
- [x] 제시어 바꾸기 #7 
- [x] 제시어를 바꾸면 문장 리셋 #8 
- [x] 제시어가 미리 정해진 목록에서 무작위로 뽑히게 하기 #9 

### 4. 한 문장 만들기 꾸미기
- [x] 글로벌 스타일 #10 
- [x] 컴포넌트 위치 잡기 #11 
- [x] 아이콘 얻어오기(Material Design Icons - [Apache 2.0 license](https://github.com/google/material-design-icons/blob/master/LICENSE) - 이용가능) #12 
- [x] 텍스트 및 아이콘 크기 조정 #13 
- [x] 배색 조정 #14 
- [x] 폰트 조정 #15 
- [x] 반응형
- [x] 세부조정 #16 

![Speak Again  page1](https://user-images.githubusercontent.com/53764714/99424512-1a8f1900-2945-11eb-8b3a-d3dec886024b.png)
![Speak Again  page2](https://user-images.githubusercontent.com/53764714/99424519-1c58dc80-2945-11eb-8705-6edb747974d3.png)
![Speak Again  page3](https://user-images.githubusercontent.com/53764714/99424526-1e22a000-2945-11eb-8cd1-f7fe88d29cb2.png)

### 5. 배포
- [x] 적절한 곳을 탐색
- [x] 최초 사용가능 버전 배포 #17 
https://codesoom.github.io/project-react-2-gringrape/

### 6. 여러 문장 만들기 & 결과 확인 구상 작업
- [x] 문장 만들기 페이지 도안 작성 - 다음 문제 버튼 위치 고려
- [x] 메인 페이지 도안 작성 - 제목, 시작하기 끝
- [x] 결과 확인 페이지 도안 작성 - 단순하게 결과 나열 끝  

### 7. 여러 문장 만들기 & 결과 확인 구현
- [x] (메인 페이지) 시작하기 버튼, 제목 표시 #19 
- [x] 라우터를 이용해서 메인페이지와 문장만들기 페이지 보여주기 #20 
- [x] (문장 만들기) 다음 문제 버튼 표시, 제목과 제시어 새로고침 버튼 삭제 #21 
- [x] (문장 만들기) 다음 문제 버튼 누르면, 답변 저장하기 #22 
- [x] (문장 만들기) 다음 문제 버튼 누르면, 다음 문제로 넘어가기 #23 
- [x] (문장 만들기) 문제를 다풀면, 종료 버튼 표시 #24 
- [x] (문장 만들기) 종료버튼을 누르면, 결과확인 페이지로 이동 #25 
- [x] 제시어 데이터 추가 #26
- [x] (메인페이지) 시작하기 버튼을 누르면, 처음 문제 표시 #27  
- [x] (결과확인) 결과 표시 #30 
- [x] (결과확인) 처음으로 버튼 표시 -> 버튼을 누르면 초기화, 메인화면으로 이동 #31 

### 8. 메인페이지, 문장 만들기, 결과확인 페이지 꾸미기
- [x] 컴포넌트 위치 잡기 #33 
- [x] 텍스트, 컴포넌트 크기 조정 #34 
- [x] 배색 조정 #35 
- [x] 반응형
- [x] 세부조정 #36 

### 타이머 기능 취소
부담스럽다는 피드백

### 9. 피드백 반영 - 문장 검사
- [ ] 문장이 제시어를 포함하는 경우 -> 제시어를 하이라이트
- [ ] 문장이 제시어를 포함하지 않는 경우 -> 부드러운 경고 ㅋ
- [ ] 맞춤법 검사 기능을 넣을 수 있는지 조사. 

### 10. 환경설정 & 배포 프로세스 설정
- [ ] 커밋 시에 단위테스트결과와 eslint 결과를 체크하도록 설정 
- [ ] 지속적으로 개선하고 배포가 이루어져야 하므로, 이럴때 쓰는 방법론을 배우기.

## 이번주가 지나면 사용자는 어떤 기능을 사용할 수 있나요?
- 말로 문장을 만들고 스스로 고칠 수 있습니다.
- ~~문장을 만들면서 남은 시간을 확인할 수 있습니다.~~
- 제시어 하나당 하나의 문장씩 총 5 문장을 만들 수 있습니다.
- 다 만든 후에 만든 결과를 확인 할 수 있습니다.

## 개인적으로 지켜야 할 수칙이 있다면?
한단위의 작업이 반영될때마다, 어플리케이션은 완성된 상태일 것. 

## 비고

**Comment by wholemann** [comment]
계획이 엄청 구체적이고 세분화 되어 있군요. 아이디어도 신선하고 기대가 큽니다ㅎㅎ

체크리스트에서 1개의 task가 하나의 PR 단위로 떨어지게 계획하면 더더욱 좋습니다.

'이번주가 지나면 사용자는 어떤 기능을 사용할 수 있나요?' 이 질문을 스스로 던지고 답한 부분이 아주 좋네요ㅎㅎ

실제로 답변하신 부분처럼 동작하려면 가장 핵심이 되는 구현부가 있을 겁니다.

하나만 해결하면 나머지가 자동으로 해결되는 작업을 찾아서 최우선적으로 해결하는 거죠.

**Comment by gringrape** [comment]
@wholemann 
> 체크리스트에서 1개의 task가 하나의 PR 단위로 떨어지게 계획하면 더더욱 좋습니다.
> 
정말이네요. 링크도 걸 수 있고, 나중에 추가작업 작성할때도 어느부분의 작업인지 레퍼런스가 되니까 좋고.
감사합니다 ㅜㅜ

**Comment by hyejineee** [comment]
방금 해봤는데 재미있어요!!🤣🤣🤣🤣

**Comment by gringrape** [comment]
@hyejineee 옷 ㅋㅋ 아무것도 없이 황량한 버전인데 해주셔서 감사합니다 ㅜ ㅋㅋㅋ
