### ISSUE TITLE
4 주차 계획

### ISSUE THREAD

**Issue by gringrape** [CodeSoom/project-react-2-gringrape#114]
## 이 앱을 언제 사용하나요?
실어증을 겪고 있는 분들이 의사소통을 연습하기 위해 사용합니다. 

### 듣고 이해하기(Yes/No)
- 사용자는 음성으로 제시되는 예/아니오로 대답할 수 있는 질문을 들을 수 있어야 합니다.
- 사용자는 화면에서 정답을 고를 수 있습니다.
- 사용자는 정답이 맞는지 확인 할 수 있어야 합니다. 

### 듣고 이해하기(Yes/No)
> 사용자가 '듣고 이해하기' 버튼을 클릭합니다.
> 화면에 재생중 표시가 나옵니다.
> '쥐는 코끼리 보다 무겁나요?' 라는 질문이 음성으로 나옵니다
> 질문이 끝나면 화면에 예 / 아니오가 표시됩니다
> 질문이 끝나면 화면에 '다시듣기'가 표시됩니다
> 사용자가 '아니오' 를 누르면 정답 효과음이 나면서 다음문제로 넘어갑니다
> 사용자가 '예'를 누르면 오답 효과음이 나면서 다음문제로 넘어갑니다

### 듣고 이해하기
**UI**
- [x] 메인 페이지에서 페이지 이동 #115 
- [x] 상태가 재생중일때, 재생 중 표시 #119 
- [x] 상태가 재생끝일때, 예/아니오 버튼 표시 #120 
- [x] 상태가 초기상태(유저 선택 전) 일때, 안내멘트 표시 #120 
- [x] 정답을 고르면 정답사운드 재생 #121 
- [x] 오답을 고르면 오답사운드 재생 #121 
- [x] 다음 문제로 넘어가기 #122 
- [x] 답을 고르면 문제와 고른 답을 저장 #123 
- [x] 결과 확인 페이지로 이동
- [x] 다음 버튼을 누르면 음성 멈추기

**Action, Service**
- [x] 플레이 중일때, 상태를 재생중으로 변경 #117 
- [x] 플레이가 끝나면, 상태를 재생끝으로 변경 #117 
- [x] 다음 문제로 넘어가기 #122 
- [x] 문제와 고른답을 저장

**데이터 추가**
- 문장 데이터 추가

### 결과확인
- [x] 문장, 정답, 내답 표시
- [x] 처음으로 버튼
- [x] 문장 옆 다시 듣기 버튼

### 피드백 반영 - 최적화, 데이터 형식
- [ ] 효율적인 데이터 저장 방법 조사 및 변경
- [ ] useCallback 복습 및 사용

### 문장 말하기
- 잘 말하고 있는지 확인이 가능해집니다
### 듣고 이해하기
- 문장을 들을 수 있게 됩니다.
- 정답을 맞출 수 있게 됩니다.
- 문제와 정답을 확인 할 수 있게 됩니다.

**Comment by gringrape** [comment]
## 마무리
- [ ] 문장 말하기 페이지 UI 수정 - 간격 수정, 배열, 경고메세지 하이라이트
- [ ] 문장 말하기 버튼 누른상태에서 넘어갈 경우 abort 처리
- [ ] 문장 말하기 입력이 인지되지 않는 경우나 오류가 발생한경우 이벤트 추가
- [ ] 문장 반복 수정, 제시어 반복 수정
- [ ] 풀 문제 갯수 정하는 페이지
- [ ] 결과 페이지 제시어 하이라이트, 문장 듣기 버튼
- [ ] 배포 수정 - 파일 복사, dist 삭제
- [ ] 훅 테스트
