### ISSUE TITLE
4주 마무리 작업

### ISSUE THREAD

**Issue by gringrape** [CodeSoom/project-react-2-gringrape#146]
## 4주 마무리 작업
- [x] 문장 말하기 페이지 UI 수정 - 간격 수정, 배열, 경고메세지 하이라이트 #140 
- [x] 문장 말하기 버튼 누른상태에서 넘어갈 경우 abort 처리 #141 
- [x] 문장 말하기 입력이 인지되지 않는 경우나 오류가 발생한경우 이벤트 추가 -> 버튼이 중복 입력되지않도록 처리 #141 
- [x] 문장 반복 수정, 제시어 반복 수정 -> 모든 제시어, 문제를 다 볼때까지 랜덤 보장 #142 
- [x] 결과 페이지 문장 듣기 버튼 #145 
- [x] 결과 페이지 제시어 하이라이트 #147 
- [x] 하이라이트 키오류 수정 -> 하이라이트가 아닌 결과 예문에서 발생한 오류 #143 
- [x] 풀 문제 갯수 정하는 페이지 #149

**Comment by gringrape** [comment]
ㅜㅜ 다음주에 계속
